# -*- coding: utf-8 -*-
"""CS01-17

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BJwmjKJ6a5Rf1da9DPCKi9fgRYFEoEHC
"""

import numpy as np
from numpy import random
x = random.randint(100, size=(5,10))
print(np.sort(x))