# -*- coding: utf-8 -*-
"""CS01-16

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jbs-Vtv_ubDtIFWtBR9XiM5FQMBieMz4
"""

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
newarr = arr.reshape(5,2,2)
print(newarr)